spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: chat-service
          uri: http://localhost:8081
          predicates:
            - Path=/chat/**
          filters:
            - TokenRelay