spring:
  application:
    name: chat-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat-service-db
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full


