spring:
  application:
    name: chat-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat-service-db
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0

server:
  port: 8081
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.jc: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG


